name: 🦑 Submit a Squid Save
description: Share your evolved squid! (Must be a .zip containing uuid.txt)
labels: ["squid-submission"]

body:
  - type: input
    id: name
    attributes:
      label: Squid Nickname
      placeholder: Squid
    validations:
      required: true

  - type: input
    id: save_url
    attributes:
      label: Save File URL
      description: |
        Do NOT drag the ZIP into this field.

        Before submitting this form, open the issue's comment box below.
        Drag your Dosidicus .zip into the comment box. GitHub will upload
        the file and display a link. Copy that link and paste it into this
        field.
      placeholder: Paste the GitHub attachment URL here
    validations:
      required: true
