name: Build Dosidicus Linux Binary for Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup PyAPP and build Dosidicus
        env:
          PYAPP_FULL_ISOLATION: 1
          PYAPP_PROJECT_NAME: dosidicus
          PYAPP_EXEC_SPEC: 'main:main'
          PYAPP_PIP_EXTRA_ARGS: 'PyQt5 numpy'
          PYAPP_DISTRIBUTION_EMBED: 1
        run: |
          poetry build
          curl -sSL https://github.com/ofek/pyapp/releases/latest/download/source.tar.gz -o pyapp-source.tar.gz
          tar -xzf pyapp-source.tar.gz
          mv pyapp-v* pyapp-latest
          cd pyapp-latest
          cargo build --release
          mv target/release/pyapp ../../dosidicus
          chmod +x ../../dosidicus

      # --- THIS STEP IS UPDATED ---
      - name: Create release zip
        run: |
          # This command now zips the executable, README, and the entire 'images' folder.
          # Make sure you have a folder named 'images' in your project's root directory.
          zip -r dosidicus-linux-amd64.zip dosidicus README.md images

      - name: Attach executable to release
        uses: softprops/action-gh-release@v2
        with:
          files: dosidicus_2.4.2-amd64-linux.zip
